### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by Tronicality** [Pifary-dev/ravel#16] opened 2024-07-23 12:18 UTC
Some people cannot use the sandbox due to a parsing issue (one of those people was RadicalLarry so I asked him to send a screenshot of inspect element)

![image](https://github.com/user-attachments/assets/786fdf24-f2f8-4e4a-9da7-f71a6669b0ab)

**Comment by sonic3XE** [comment] 2024-07-24 15:27
it may be coming from tick delay and input delay whenever you leave those values empty. It's easy to reproduce lol since the default values are not automatically assigned when the value is empty.

**Comment by Pifary-dev** [comment] 2024-07-30 13:03
Should be fixed now if it's tick or input delay

**Closed as completed by Pifary-dev** 2024-07-30 13:03 UTC
